BookApp/Entities/CommentReport.cs
namespace BookApp.Entities
{
    public class CommentReport : BaseEntity
    {
        public string UserId { get; set; }
        public User User { get; set; }
        public string CommentId { get; set; } 
        public Comment Comment { get; set; }
        public string AdditionalComment { get; set; }
        public ICollection<CommentReportFlag> CommentReportFlags { get; set; } = new HashSet<CommentReportFlag>();
    }
}

BookApp/Entities/Dtos/CommentReport/CommentReportDto.cs
namespace BookApp.Entities.Dtos.CommentReport;

public class CommentReportDto
{
    public string Id { get; set; }
    public string AdditionalComment { get; set; }
    public string CommentId { get; set; }
    public string UserId { get; set; }
    public string CommentReporter { get; set; }
    public string CommentText { get; set; }
    public string FlagId { get; set; }
    public List<string> FlagNames { get; set; } = new List<string>();
}

BookApp/Models/CommentReport/CommentReportResponseModel.cs
namespace BookApp.Models.CommentReport;

public class CommentReportResponseModel : BaseResponseModel
{
    public CommentReportViewModel Data { get; set; }
}

public class CommentReportsResponseModel : BaseResponseModel
{
    public List<CommentReportViewModel> Data { get; set; }
}

BookApp/Models/CommentReport/CommentReportViewModel.cs
namespace BookApp.Models.CommentReport;

public class CommentReportViewModel
{
    public string Id { get; set; }
    public string AdditionalComment { get; set; }
    public string CommentId { get; set; }
    public string UserId { get; set; }
    public string CommentReporter { get; set; }
    public string CommentText { get; set; }
    public string FlagId { get; set; }
    public List<string> FlagNames { get; set; } = new List<string>();
}

BookApp/Models/CommentReport/CreateCommentReportViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BookApp.Models.CommentReport;

public class CreateCommentReportViewModel
{
    public string CommentId { get; set; }
    public string UserId { get; set; }
    public List<string> FlagIds { get; set; } = new List<string>();
    public string BookId { get; set; }
    [Required(ErrorMessage = "Comment text cannot be empty")]
    [MinLength(20, ErrorMessage = "The minimum length is 20.")]
    [MaxLength(200, ErrorMessage = "The Maximum length is 200.")]
    public string AdditionalComment { get; set; }
}

BookApp/Models/CommentReport/UpdateCommentReportViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BookApp.Models.CommentReport;

public class UpdateCommentReportViewModel
{
    public int Id { get; set; }
    [Required(ErrorMessage = "Comment text cannot be empty")]
    [MinLength(3, ErrorMessage = "The minimum lenghth is 3.")]
    [MaxLength(200, ErrorMessage = "The Maximum lenghth is 200.")]
    public string AdditionalComment { get; set; }
}

BookApp/Controllers/CommentController.cs
using BookApp.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using BookApp.Models.Comment;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace BookApp.Controllers;

public class CommentController : Controller
{
    private readonly ICommentService _commentService;
    private readonly INotyfService _notyf;

    public CommentController(ICommentService commentService, INotyfService notyf)
    {
        _commentService = commentService;
        _notyf = notyf; 
    }

    //public IActionResult Index()
    //{
    //    var response = _commentService.GetAllComment();
    //    ViewData["Message"] = response.Message;
    //    ViewData["Status"] = response.Status;

    //    return View(response.Data);
    //}

    public async Task<IActionResult> GetCommentDetail(string id)
    {
        var response = await _commentService.GetComment(id);

        if (response.Status is false)
        {
            _notyf.Error(response.Message);
            return RedirectToAction("Index", "Question");
        }

        return View(response.Data);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(CreateCommentViewModel request)
    {
        var response = await _commentService.CreateComment(request);

        if(response.Status is false)
        {
            _notyf.Error(response.Message);
            return View();
        }

        _notyf.Success(response.Message);

        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> Update(string id)
    {
        var response = await _commentService.GetComment(id);

        if (response.Status is false)
        {
            _notyf.Error(response.Message);
            return RedirectToAction("Index", "Home");
        }

        return View(response.Data);
    }

    [HttpPost]
    public async Task<IActionResult> Update(string id, UpdateCommentViewModel request)
    {
        var response = await _commentService.UpdateComment(id, request);

        if (response.Status is false)
        {
            _notyf.Error(response.Message);
            return RedirectToAction("Index", "Home");
        }

        _notyf.Success(response.Message);

        return RedirectToAction("Index", "Home");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteComment([FromRoute] string id)
    {
        var response = await _commentService.DeleteComment(id);

        if (response.Status is false)
        {
            _notyf.Error(response.Message);
            return RedirectToAction("Index", "Home");
        }

        _notyf.Success(response.Message);

        return RedirectToAction("Index", "Home");
    }
}

BookApp/Controllers/CommentReportController.cs
using BookApp.Models.CommentReport;
using BookApp.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookApp.Controllers
{
    [Authorize]
    public class CommentReportController : Controller
    {
        private readonly ICommentReportService _commentReportService;
        private readonly IFlagService _flagService;

        public CommentReportController(
            ICommentReportService commentReportService, 
            IFlagService flagService)
        {
            _commentReportService = commentReportService;
            _flagService = flagService;
        }

   //     public IActionResult Index()
   //     {
   //         var response = _commentReportService.GetAllCommentReport();
			//ViewData["Message"] = response.Message;
			//ViewData["Status"] = response.Status;
   //         return View(response.Data);
   //     }

        public async Task<IActionResult> CreateCommentReport()
        {
            ViewBag.FlagLists = await _flagService.SelectFlags();
            ViewData["Message"] = "";
            ViewData["Status"] = false;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCommentReport(CreateCommentReportViewModel request)
        {
            var response = await _commentReportService.CreateCommentReport(request);
			ViewData["Message"] = response.Message;
			ViewData["Status"] = response.Status;

			return View();
        }

        public async Task<IActionResult> GetCommentReportDetail(string id)
        {
            var response = await _commentReportService.GetCommentReport(id);
			ViewData["Message"] = response.Message;
			ViewData["Status"] = response.Status;

			return View(response.Data);
        }

        public async Task<IActionResult> UpdatecommentReport(string id)
        {
            var response = await _commentReportService.GetCommentReport(id);
            return View(response.Data);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCommentReport(string id, UpdateCommentReportViewModel request)
        {
            var response = await _commentReportService.UpdateCommentReport(id, request);
			ViewData["Message"] = response.Message;
			ViewData["Status"] = response.Status;
			return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCommentReport(string id)
        {
            var response = await _commentReportService.DeleteCommentReport(id);
			ViewData["Message"] = response.Message;
			ViewData["Status"] = response.Status;

            return RedirectToAction("Index");
        }
    }
}

BookApp/Views/CommentReport/CreateCommentReport.cshtml
@model BookApp.Models.CommentReport.CreateCommentReportViewModel

@{
    ViewData["Title"] = "Report Comment";
    var commentId = ViewContext.RouteData.Values["id"];
}

@section Styles {
    @{
        await Html.RenderPartialAsync("_Select2CssPartial");
    }
}

<div class="body">

    @await Html.PartialAsync("_NoModelAlert")

    <div class="row">
        <div class="col-md-6">
            <form asp-action="CreateCommentReport" asp-controller="CommentReport">
                <input type="hidden" class="form-control" name="CommentId" value="@commentId" />

                <div class="col-md-12 mb-3">
                    <select type="checkbox" class="form-control" multiple="multiple"
                            name="FlagIds" required="required"
                            asp-items="@ViewBag.FlagLists"
                            data-placeholder="Select Flag">
                    </select>
                </div>

                <div class="col-md-12 mb-3">
                    <label asp-for="AdditionalComment" class="control-label"></label>
                    <textarea asp-for="AdditionalComment" class="form-control"></textarea>
                    <span asp-validation-for="AdditionalComment" class="text-danger"></span>
                </div>

                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Report Comment</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_Select2JsPartial");
    }
}

BookApp/Views/CommentReport/GetCommentReportDetail.cshtml
@model BookApp.Models.CommentReport.CommentReportViewModel

@{
    ViewData["Title"] = "Comment Report Details";
}

@await Html.PartialAsync("_Alert", Model)

@if (Model is not null)
{
    <div class="body">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-comment text-info"></i>
                            @ViewData["Title"]
                        </h3>
                    </div>

                    <div class="card-body">
                        <dl class="row">
                            <dt class="col-md-4">CommentReporter:</dt>
                            <dd class="col-md-8">@Model.CommentReporter</dd>
                            <dt class="col-md-4">CommentText:</dt>
                            <dd class="col-md-8">@Model.CommentText</dd>
                            <dt class="col-md-4">Additional Comment:</dt>
                            <dd class="col-md-8">@Model.AdditionalComment</dd>
                            <dt class="col-md-4">FlagNames:</dt>
                            <dd class="col-md-8">
                                @foreach(var flag in Model.FlagNames)
                                {
                                    <i class="badge bg-dark">@flag</i>
                                }
                            </dd>
                        </dl>

                        <div class="btn-group">
                            <a class="btn btn-primary" asp-controller="Comment" asp-action="GetCommentDetail" asp-route-id="@Model.CommentId">Go back</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}

BookApp/Views/CommentReport/Index.cshtml
@model List<BookApp.Models.CommentReport.CommentReportViewModel>
@{
    ViewData["Title"] = "CommentReport List";
    int count = 1;
}

@await Html.PartialAsync("_ListAlert", Model)

@if (Model is not null)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">CommentReporter</th>
                <th scope="col">AdditionalComment</th>
                <th scope="col">Action</th>
            </tr>
        </thead>

        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@count</th>
                    <td>@item.CommentReporter</td>
                    <td>@item.AdditionalComment</td>
                    <td>
                        <div class="btn-group">
                            <a asp-controller="CommentReport" asp-action="GetCommentReportDetail" asp-route-id="@item.Id" class="btn btn-primary">
                                View
                            </a>
                        </div>
                    </td>
                </tr>
                count++;
            }
        </tbody>
    </table>
}

BookApp/Views/CommentReport/UpdateCommentReport.cshtml
@model BookApp.Models.CommentReport.UpdateCommentReportViewModel
@{
	ViewData["Title"] = "Edit CommentReport";
}

@await Html.PartialAsync("_Alert", Model)

@if (Model is not null)
{
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-6">
					<form asp-action="UpdateCommentReport" asp-route-id="@Model.Id">
						<div asp-validation-summary="ModelOnly" class="text-danger"></div>
						<input type="hidden" asp-for="Id" />
						<div class="form-group">
							<label asp-for="AdditionalComment" class="control-label"></label>
							<input asp-for="AdditionalComment" class="form-control" value="@Model.AdditionalComment" />
							<span asp-validation-for="AdditionalComment" class="text-danger"></span>
						</div>

						<div class="form-row">
							<div class="kt-form__actions">
								<button class="btn btn-success"
										type="submit">
									Save Changes
								</button>
								&nbsp;
								<a class="btn btn-primary" asp-action="GetCommentReportDetail" asp-route-id="@Model.Id">
									Back to Details
								</a>
								&nbsp;
								<a class="btn btn-primary"
								   asp-action="GetCommentReport">
									Back to  List
								</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</section>
}