BookApp/Entities/BookReport.cs
using BookApp.Entities;

namespace BookApp.Entities
{
    public class BookReport : BaseEntity
    {
        public string UserId { get; set; }
        public User User { get; set; }
        public string BookId { get; set; }
        public Book Book { get; set; }
        public string AdditionalComment { get; set; }
        public ICollection<BookReportFlag> BookReportFlags { get; set; } = new HashSet<BookReportFlag>();
    }
}

BookApp/Entities/Dtos/BookReport/BookReportDto.cs
namespace BookApp.Entities.Dtos.QuestionReport
{
    public class BookReportDto
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string BookId { get; set; }
        public string BookReporter { get; set; }
        public string AdditionalComment { get; set; }
        public string BookText { get; set; }
        public List<string> FlagNames { get; set; } = new List<string>();
    }
}

BookApp/Models/BookReport/BookReportResponseModel.cs
namespace BookApp.Models.BookReport;

public class BookReportResponseModel : BaseResponseModel
{
    public BookReportViewModel Data { get; set; }
}

public class BookReportsResponseModel : BaseResponseModel
{
    public List<BookReportViewModel> Data { get; set; }
}

BookApp/Models/BookReport/BookReportViewModel.cs
namespace BookApp.Models.BookReport;

public class BookReportViewModel
{
    public string Id { get; set; }
    public string UserId { get; set; }
    public string BookId { get; set; }
    public string BookReporter { get; set; }
    public string AdditionalComment { get; set; }
    public string BookText { get; set; }
    public List<string> FlagNames { get; set; } = new List<string>();
}

BookApp/Models/BookReport/CreateBookReportViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BookApp.Models.BookReport;

public class CreateBookReportViewModel
{
    public string UserId { get; set; }
    public string BookId { get; set; }

    [Required(ErrorMessage = "One or more books need to be selected")]
    public List<string> FlagIds { get; set; } = new List<string>();
    [Required(ErrorMessage = " Comment text required")]
    [MinLength(20, ErrorMessage = "Minimum of 20 character required")]
    [MaxLength(150, ErrorMessage = "Maximum of 150 character required")]
    public string AdditionalComment { get; set; }
}

BookApp/Models/BookReport/UpdateBookReportViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BookApp.Models.BookReport;

public class UpdateBookReportViewModel
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public int BookId { get; set; }
    [Required(ErrorMessage = " Comment text required")]
    [MinLength(20, ErrorMessage = "Minimum of 20 character required")]
    [MaxLength(150, ErrorMessage = "Maximum of 150 character required")]
    public string AdditionalComment { get; set; }
}

BookApp/Controllers/BookReportController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BookApp.Models.BookReport;
using BookApp.Service.Implementations;
using BookApp.Service.Interface;
using Microsoft.AspNetCore.Mvc;

namespace BookApp.Controllers
{
    public class BookReportController : Controller
    {
        private readonly IBookReportService _bookReportService;
        private readonly INotyfService _notyf;
        private readonly IFlagService _flagService;

        public BookReportController(
            IBookReportService bookReportService,
            IFlagService flagService,
            INotyfService notyf)
        {
            _bookReportService = bookReportService;
            _notyf = notyf;
            _flagService = flagService;
        }

        //public IActionResult Index()
        //{
        //    var response = _questionReportService.GetAllQuestionReport();
        //    ViewBag.Message = response.Message;
        //    ViewBag.status = response.Status;

        //    return View(response.Data);
        //}

        //    return RedirectToAction("Index", "QuestionReport");
        //}

        public async Task<IActionResult> ReportBook()
        {
            ViewBag.FlagLists = await _flagService.SelectFlags();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ReportBook(CreateBookReportViewModel Report)
        {
            var response = await _bookReportService.CreateBookReport(Report);

            if (response.Status is false)
            {
                return View(response);
            }

            _notyf.Success(response.Message);

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> GetBookReport(string id)
        {
            var response = await _bookReportService.GetBookReport(id);

            if (response.Status is false)
            {
                _notyf.Error(response.Message);

                return RedirectToAction("Index", "Book");
            }

            return View(response.Data);
        }

        public async Task<IActionResult> GetBookReports(string id)
        {
            var response = await _bookReportService.GetBookReports(id);

            if (response.Status is false)
            {
                _notyf.Error(response.Message);
                return RedirectToAction("Index", "Book");
            }

            return View(response.Data);
        }

        public async Task<IActionResult> UpdateBookReport(string id)
        {
            var response = await _bookReportService.GetBookReport(id);

            if (response.Status is false)
            {
                _notyf.Error(response.Message);
                return RedirectToAction("Index", "Book");
            }

            return RedirectToAction("Index", "Book");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBookReport(string id, UpdateBookReportViewModel request)
        {
            var response = await _bookReportService.UpdateBookReport(id, request);

            if (response.Status is false)
            {
                _notyf.Error(response.Message);
                return RedirectToAction("Index", "Book");
            }

            _notyf.Success(response.Message);
            return RedirectToAction("Index", "Book");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBookReport(string id)
        {
            var response = await _bookReportService.DeleteBookReport(id);

            if (response.Status is false)
            {
                _notyf.Error(response.Message);
                return RedirectToAction("Index", "Book");
            }

            _notyf.Success(response.Message);

            return RedirectToAction("Index", "Book");
        }
    }
}

BookApp/Views/BookReport/GetBookReport.cshtml
@model BookApp.Models.BookReport.BookReportViewModel
@{
    ViewData["Title"] = "Book Report Detail";
}

<h3 class="card-title">
    @ViewData["Title"]
</h3>

<div class="card-body">
    <dl class="row">
        <dt class="col-sm-4">AdditionalComment</dt>
        <dd class="col-sm-8">@Model.AdditionalComment</dd>
        <dt class="col-sm-4">FlagNames</dt>
        <dt class="col-sm-8">
            @foreach (var flag in Model.FlagNames)
            {
                <i class="badge bg-dark">@flag</i>
            }
        </dt>
    </dl>

    @* <a class="btn btn-success" asp-action="UpdateQuestionReport" asp-controller="QuestionReport" asp-route-id="@Model.Id">update</a>

    &nbsp;
    <a class="btn btn-primary" asp-action="Index" asp-controller="QuestionReport">Back to List</a>
    &nbsp;
    <hr />
    <form asp-action="DeleteQuestionReport" asp-controller="QuestionReport" asp-route-id="@Model.Id">
    <button type="submit" class="btn btn-danger">Delete</button>
    </form>*@
    <a asp-controller="BookReport" asp-action="GetBookReports" asp-route-id="@Model.BookId" class="btn btn-success">Back</a>
</div>

BookApp/Views/BookReport/GetBookReports.cshtml
@model List<BookApp.Models.BookReport.BookReportViewModel>

@{
    ViewData["Title"] = "View Book Reports";
    var count = 1;
}

@if (Model is not null)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Flag</th>
                <th scope="col">Reporter</th>
                <th scope="col">Action</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td scope="row">@count</td>
                    <td scope="row">
                        @foreach(var flag in item.FlagNames)
                        {
                            <i class="badge bg-black">@flag</i>
                        }
                    </td>
                    <td scope="row">@item.BookReporter</td>

                    <td scope="row">
                        <a asp-controller="BookReport" asp-action="GetBookReport" asp-route-id="@item.Id">View Report Detail</a>
                    </td>
                </tr>
                count++;
            }
        </tbody>
    </table>

    <div>
        <a asp-controller="Book" asp-action="Index" class="btn btn-secondary">
            Back
        </a>
    </div>
}

BookApp/Views/BookReport/Index.cshtml
@model List<BookApp.Models.BookReport.BookReportViewModel>
@{
    ViewData["Title"] = "Report List";
    int count = 1;
    var status = ViewBag.Status == false ? false : true;
}

 @await Html.PartialAsync("_ListAlert", Model)

@if (status is false)
{
    <span>@ViewBag.Message</span>
    return;
}
<table class="table">
     <thead>
          <tr>
               <th scope="col">#</th>
               <th scope="col">AdditionalComment</th>
               <th scope="col">Action</th>
          </tr>
     </thead>

     <tbody>

        @foreach (var item in Model)
        {
              <tr>
                   <th scope="row">@count</th>
                   <td>@item.AdditionalComment</td>
                   <td>
                        <div class="btn-group">
                        <a asp-controller="BookReport" asp-action="GetBookReport" asp-route-id="@item.Id" class="btn btn-primary">View Reports</a>
                        </div>
                   </td>
              </tr>
            count++;
        }
     </tbody>
</table>

BookApp/Views/BookReport/ReportBook.cshtml
@model BookApp.Models.BookReport.CreateBookReportViewModel
@{
    ViewData["Title"] = "Create New Book Report";
    var bookId = ViewContext.RouteData.Values["id"];
}

@section Styles {
    @{
        await Html.RenderPartialAsync("_Select2CssPartial");
    }
}

<div class="body">

    <div class="row">
        <div class="col-md-6">
            <form asp-action="ReportBook" asp-controller="BookReport">
                <input type="hidden" class="form-control" name="BookId" value="@bookId" />

                <div class="col-md-12 mb-3">
                    <select type="checkbox" class="form-control" multiple="multiple"
                            name="FlagIds" required="required"
                            data-placeholder="Select Book Flags"
                            asp-items="@ViewBag.FlagLists">
                    </select>
                </div>

                <div class="col-md-12 mb-3">
                    <label asp-for="AdditionalComment" class="control-label"></label>
                    <textarea asp-for="AdditionalComment" class="form-control"></textarea>
                    <span asp-validation-for="AdditionalComment" class="text-danger"></span>
                </div>

                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Report Book</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_Select2JsPartial");
    }
}

BookApp/Views/BookReport/UpdateBookReport.cshtml
@model BookApp.Models.BookReport.BookReportViewModel
@{
	ViewData["Title"] = "Update BookReport";
}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-6">
		   <form asp-action="Update">

				<div class="form-group"> 
					<label asp-for="AdditionalComment" class="control-label"></label>
						 <input asp-for="AdditionalComment" type="text" class="form-control" value="@Model.AdditionalComment" /><br />
						 <span asp-validation-for="AdditionalComment" class="text-danger"></span>
				</div>
			 <div class="col-md-12">
				 <button type="submit" class="btn btn-primary">Update</button>
			 </div>
			</form>
		</div>
	</div>
</div>